name: flutter_firebase
description: "A Flutter Firebase project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  grouped_list: ^6.0.0
  flutter_linkify: ^6.0.0
  intl: ^0.19.0
  http: ^1.2.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  firebase_storage: ^12.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
